# Generated by Django 5.2.1 on 2025-05-15 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="hotel",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
