# Generated by Django 5.2.1 on 2025-05-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0002_menu_hotel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="name",
            new_name="dish_name",
        ),
    ]
