# Generated by Django 5.2.1 on 2025-05-21 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0003_rename_name_menu_dish_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_category_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="menuapp.menucategory",
            ),
        ),
    ]
